### PR TITLE
removed files

### LINKED ISSUE #39: Issues from TBD and TODO files
The TBD file contains:

```
o Merge nestedomp branch into trunk
  - Requires better understanding of OMP standard on nesting
o Refactor or clean-slate testing procedure
  - More, shorter tests
  - "make test" should only build what is going to be run
  - Overload specific tests only when necessary
  - Rewrite runalltests* in Perl
o Update PAPI interface to latest PAPI rev.
o Better handling of MPI vs. no MPI
  - Best not to have pr_summary take different arguments
o Possible to employ iso_c_binding?
o Enable *threadohd_outer and *threadohd_inner in C, thus enabling to invoke
  from C
o For THREADED_PTHREADS, improve speed of finding threadid
o Update web pages and man pages
o Enable XML output (collapse/expand tree hierarchy)
o Bug in ??? output?
o Why does C++ test break when use prototypes for pr_summary*?
o "make clean" should always get rid of everything that might have been built
o GPU port

```

To TODO file has:

```
o For THREADED_PTHREADS, improve speed of finding threadid
o Why does C++ test break when use prototypes for pr_summary*?
o Update to C standard allowing stack vars dimensioned by input args.
o "make clean" should always get rid of everything that might have been built
o Revamp test suite. Suggestions:
  - More, shorter tests
  - "make test" should only build what is going to be run
  - Overload specific tests only when necessary
  - Rewrite runalltests* in Perl
o GPU port
o Merge nested OMP to trunk, possibly enabling at compile-time if cost is
  high
  
```

Some of these have been achieved, some are no longer relevant, some are associate with the fortran library and some are C library tasks that should be made into github issues. Then we can delete these files.

### PR DESCRIPTION
**Pull request by edhartnett**
Part of #39.

Just removed the files. These are now in the github issue. Break out any that are still relevant to their own issues, and then close #39.

### CODE REVIEW

**Comment by edhartnett** [comment]
I think that I have nothing else to do for the C library in terms of autotoolization. I am now going to move on to the Fortran library...

**Comment by edhartnett** [comment]
@jmrosinski I am going to merge this today, if you have no objections.

**Comment by jmrosinski** [comment]
Yes as long as the contents of those files are preserved somewhere I have
no objections. I need to update the contents since big changes to the lib
are ongoing.

That's great you're going to have a look at the Fortran lib. That was on my
list, but since you're going to have at it first, I'll continue with
looking at C++ization.

Jim

**Comment by edhartnett** [comment]
The references to the fortran lib are out of date. It is complete and working well.

I will merge this PR.

These files of course always live on in git for future reference. You should transfer the active contents to github issues.

**Pull request merged**
